# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: pushsign/hasd-db:local
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "hasd_db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data"
volumes:
  hasd_db_data:
    external: true
